/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Paneles;

import Modelo.Entidades.Equipo;
import Modelo.Entidades.Falla;
import Modelo.Entidades.FallaObservada;
import Modelo.Entidades.OrdenDeTrabajoPreventivo;
import Controlador.ControladorOrdenesPreventivo;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Window;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class AgregarOrdenPreventiva extends javax.swing.JPanel {

    ControladorOrdenesPreventivo controlador;
    //modal equipos
    JFrame modalEquipos;
    JList listaEquipos;
    DefaultListModel<Equipo> modeloEquipos = new DefaultListModel<>();
    Equipo equipoSeleccionado;
    /**
     * Creates new form AgregarOrdenPreventiva
     */
    public AgregarOrdenPreventiva() {
        controlador = new ControladorOrdenesPreventivo();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSeleccionarEquipo = new javax.swing.JButton();
        lblEquipoActual = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputFechaEjecucion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        jLabel1.setText("Equipo seleccionado:");

        btnSeleccionarEquipo.setText("Seleccionar Equipo");
        btnSeleccionarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarEquipoMouseClicked(evt);
            }
        });
        btnSeleccionarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarEquipoActionPerformed(evt);
            }
        });

        lblEquipoActual.setText("No se ha seleccionado ninguno");

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        jLabel2.setText("Fecha de ejecución:");

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSeleccionarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputFechaEjecucion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnVolver)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAgregar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEquipoActual)
                                    .addComponent(jLabel1))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSeleccionarEquipo))
                .addGap(18, 18, 18)
                .addComponent(lblEquipoActual)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputFechaEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnAgregar))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarEquipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO
        Window w = SwingUtilities.getWindowAncestor(this);
            if (w != null) w.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO
        try{

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            OrdenDeTrabajoPreventivo orden = new OrdenDeTrabajoPreventivo();
            orden.setIdEquipo(equipoSeleccionado.getId());
            orden.setFechaEjecucion(sdf.parse(inputFechaEjecucion.getText()));

            if (controlador.Agregar(orden))
                JOptionPane.showMessageDialog(null,"Esta orden fue agregada con éxito", "Realizado con éixto", JOptionPane.INFORMATION_MESSAGE);;
        }
        catch(ParseException e){
            JOptionPane.showMessageDialog(null, "Fallo al agregar: Formato de fecha incorrecto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Fallo al agregar: Llame a Dios. "+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnSeleccionarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarEquipoMouseClicked
        // TODO
        BuscarEquipo();
    }//GEN-LAST:event_btnSeleccionarEquipoMouseClicked

    private void BuscarEquipo(){
        JLabel lblEqSeleccion = new JLabel();
        //Carga el modal
        modalEquipos = new JFrame("Buscar Equipo");
        modalEquipos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JPanel contenido = new  JPanel();
        contenido.setLayout(new BoxLayout(contenido, BoxLayout.Y_AXIS));
        JPanel panelLista = new JPanel(new BorderLayout());
        modeloEquipos = new DefaultListModel<>();
        modeloEquipos.addAll(controlador.BuscarTodosEquipos());
        listaEquipos = new JList(modeloEquipos);
        listaEquipos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaEquipos.addListSelectionListener(e ->{
            if(!e.getValueIsAdjusting()){
                equipoSeleccionado = (Equipo)modeloEquipos.get(listaEquipos.getSelectedIndex());
                lblEqSeleccion.setText(equipoSeleccionado.toString());
                lblEqSeleccion.revalidate();
                lblEqSeleccion.repaint();
                lblEquipoActual.setText(equipoSeleccionado.toString());
                lblEquipoActual.revalidate();
                lblEquipoActual.repaint();
            }
        });
        panelLista.add(new JScrollPane(listaEquipos),  BorderLayout.CENTER);
        contenido.add(panelLista);

        JPanel panelInferior = new JPanel(new GridLayout(1, 2, 10, 0));

        JPanel panelBotones = new JPanel();
        JButton btnVolver = new JButton("Volver");
        btnVolver.setFont(new Font("Arial", Font.BOLD, 15));
        btnVolver.addActionListener(e -> {
            modalEquipos.dispose();
        });
        panelBotones.add(btnVolver);
        panelInferior.add(panelBotones);

        JPanel panelTxtEqSelec = new JPanel();
        panelTxtEqSelec.setLayout(new BoxLayout(panelTxtEqSelec, BoxLayout.Y_AXIS));
        JLabel tituloEqSelec = new JLabel("Equipo seleccionado:");
        tituloEqSelec.setFont(new Font("Arial", Font.BOLD, 17));
        tituloEqSelec.setAlignmentX(0);
        panelTxtEqSelec.add(tituloEqSelec);
        lblEqSeleccion.setFont(new Font("Arial", Font.PLAIN, 15));
        if(equipoSeleccionado == null)
            lblEqSeleccion.setText("No se ha seleccionado ninguno.");
        else{
            lblEqSeleccion.setText(equipoSeleccionado.toString());
        }
        lblEqSeleccion.revalidate();
        lblEqSeleccion.repaint();

        lblEqSeleccion.setAlignmentX(0);
        panelTxtEqSelec.add(lblEqSeleccion);
        panelInferior.add(panelTxtEqSelec);

        modalEquipos.add(contenido, BorderLayout.CENTER);
        modalEquipos.add(panelInferior, BorderLayout.SOUTH);
        modalEquipos.pack();
        modalEquipos.setLocationRelativeTo(null);
        modalEquipos.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSeleccionarEquipo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField inputFechaEjecucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEquipoActual;
    // End of variables declaration//GEN-END:variables
}










